######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 23 11:52:17 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += azom.h \
           bullet.h \
           fastseekzom.h \
           gzom.h \
           mcon.h \
           object.h \
           player.h \
           seekzom.h \
           shootzom.h \
           szom.h \
           weapon.h \
           zomzom.h \
           zomzomattack.h \
           zomzomattackwindow.h
SOURCES += main.cpp \
           object.cpp \
           player.cpp \
           shootzom.cpp \
           zomzomattack.cpp \
           zomzomattackwindow.cpp
