#############################################################################
# Makefile for building: hw5
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Apr 23 11:52:19 2012
# Project:  hw5.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile hw5.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		object.cpp \
		player.cpp \
		shootzom.cpp \
		zomzomattack.cpp \
		zomzomattackwindow.cpp moc_zomzomattack.cpp \
		moc_zomzomattackwindow.cpp
OBJECTS       = main.o \
		object.o \
		player.o \
		shootzom.o \
		zomzomattack.o \
		zomzomattackwindow.o \
		moc_zomzomattack.o \
		moc_zomzomattackwindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hw5.pro
QMAKE_TARGET  = hw5
DESTDIR       = 
TARGET        = hw5

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hw5.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile hw5.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile hw5.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hw51.0.0 || $(MKDIR) .tmp/hw51.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hw51.0.0/ && $(COPY_FILE) --parents azom.h bullet.h fastseekzom.h gzom.h mcon.h object.h player.h seekzom.h shootzom.h szom.h weapon.h zomzom.h zomzomattack.h zomzomattackwindow.h .tmp/hw51.0.0/ && $(COPY_FILE) --parents main.cpp object.cpp player.cpp shootzom.cpp zomzomattack.cpp zomzomattackwindow.cpp .tmp/hw51.0.0/ && (cd `dirname .tmp/hw51.0.0` && $(TAR) hw51.0.0.tar hw51.0.0 && $(COMPRESS) hw51.0.0.tar) && $(MOVE) `dirname .tmp/hw51.0.0`/hw51.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hw51.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_zomzomattack.cpp moc_zomzomattackwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_zomzomattack.cpp moc_zomzomattackwindow.cpp
moc_zomzomattack.cpp: szom.h \
		zomzom.h \
		object.h \
		azom.h \
		gzom.h \
		seekzom.h \
		fastseekzom.h \
		shootzom.h \
		mcon.h \
		weapon.h \
		player.h \
		bullet.h \
		zomzomattack.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) zomzomattack.h -o moc_zomzomattack.cpp

moc_zomzomattackwindow.cpp: zomzomattack.h \
		szom.h \
		zomzom.h \
		object.h \
		azom.h \
		gzom.h \
		seekzom.h \
		fastseekzom.h \
		shootzom.h \
		mcon.h \
		weapon.h \
		player.h \
		bullet.h \
		zomzomattackwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) zomzomattackwindow.h -o moc_zomzomattackwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp zomzomattackwindow.h \
		zomzomattack.h \
		szom.h \
		zomzom.h \
		object.h \
		azom.h \
		gzom.h \
		seekzom.h \
		fastseekzom.h \
		shootzom.h \
		mcon.h \
		weapon.h \
		player.h \
		bullet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

object.o: object.cpp object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o object.cpp

player.o: player.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

shootzom.o: shootzom.cpp shootzom.h \
		zomzom.h \
		object.h \
		zomzomattack.h \
		szom.h \
		azom.h \
		gzom.h \
		seekzom.h \
		fastseekzom.h \
		mcon.h \
		weapon.h \
		player.h \
		bullet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shootzom.o shootzom.cpp

zomzomattack.o: zomzomattack.cpp zomzomattack.h \
		szom.h \
		zomzom.h \
		object.h \
		azom.h \
		gzom.h \
		seekzom.h \
		fastseekzom.h \
		shootzom.h \
		mcon.h \
		weapon.h \
		player.h \
		bullet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zomzomattack.o zomzomattack.cpp

zomzomattackwindow.o: zomzomattackwindow.cpp zomzomattackwindow.h \
		zomzomattack.h \
		szom.h \
		zomzom.h \
		object.h \
		azom.h \
		gzom.h \
		seekzom.h \
		fastseekzom.h \
		shootzom.h \
		mcon.h \
		weapon.h \
		player.h \
		bullet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zomzomattackwindow.o zomzomattackwindow.cpp

moc_zomzomattack.o: moc_zomzomattack.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zomzomattack.o moc_zomzomattack.cpp

moc_zomzomattackwindow.o: moc_zomzomattackwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zomzomattackwindow.o moc_zomzomattackwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

